QT += core gui quick quickcontrols2 network sql dbus concurrent opengl
CONFIG += c++20 link_pkgconfig
TARGET = yunjian
TEMPLATE = app
PKGCONFIG += mpv libsecret-1 openssl libqrencode taglib zlib
SOURCES += src/main.cpp src/crypto.cpp src/session.cpp src/backend.cpp src/videoitem.cpp src/mpris.cpp
HEADERS += src/crypto.h src/session.h src/backend.h src/videoitem.h src/mpris.h
RESOURCES += resources.qrc
QMAKE_CXXFLAGS += -Wall -Wextra
